project:
  type: website

website:
  title: "Sam Harper"
  site-url: "https://www.samharper.org"
  repo-url: "https://github.com/sbh4th/qweb"
  navbar:
    search: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Teaching"
        file: teaching/index.qmd
      - text: "Posts"
        file: posts/index.qmd
      - text: "Talks"
        file: talks/index.qmd
      - text: "Projects"
        file: projects/index.qmd
      - text: "Papers"
        file: publications/index.qmd
      - text: "CV"
        file: cv/index.qmd

format:
  html:
    theme: materia
    css: styles.css
    toc: true

editor: visual

