project:
  type: website

website:
  title: "Sam Harper"
  site-url: "https://www.samharper.org"
  repo-url: "https://github.com/sbh4th/qweb"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Teaching"
        file: teaching/index.qmd
      - text: "Posts"
        file: blog/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

