---
title: "Papers"
execute: 
  echo: false
  message: false
  warning: false
page-layout: full
include-back-link: false
toc-location: right
cache: false
---

```{r setup}
library(here)
library(htmltools)
source(here("_common.R"))

pubs <- get_pubs()
```

## Recent Journal Articles
*indicates trainee under my supervision or co-supervision.

`r make_pub_list(pubs, "ARTICLE")`

## Book Chapters

`r make_pub_list(pubs, "INCOLLECTION")`

## Media mentions
- Our recent [paper](https://www.tandfonline.com/doi/full/10.1080/13607863.2025.2473634) on loneliness led by my former PhD student [Robin Richardson](https://www.robinarichardson.com/) (co-supervised with Arijit Nandi) was covered in over [280 outlets](https://newsroom.taylorandfrancisgroup.com/study-middle-aged-americans-are-lonelier-than-adults-in-other-countries-age-groups/) such as *ABC News*, *CNN*, *New York Post*, and *Euro News*, 2025-04-22.
- Coverage by [*The Indian Express*](https://indianexpress.com/article/india/extreme-wet-conditions-linked-to-increase-in-suicides-in-rural-india-study-6601839/) and [*Forbes*](https://www.forbes.com/sites/dishashetty/2020/09/24/droughts-floods-linked-to-mental-health-finds-new-study/#6529641a10f4) on our recent paper investigating environmental conditions and suicide in India, 2020-09-19. 
- [Report](https://www.theleafnews.com/news/do-fatal-car-crashes-actually-increase-on-420-not-so-fast-says-new-research-506836442.html) by *The Leaf News* on our [paper]({{< ref "/publication/harper-2019-ac/index.md" >}}) looking at the cannabis "holiday" on April 20 and fatal traffic crashes, 2019-03-07.
- Feature (and interview) on the [Smarter Choices for Better Health Initiative](https://www.eur.nl/en/news/even-netherlands-has-important-differences-between-health-poor-and-rich-we-would-decrease), 2018-11-26.
- Coverage of our [paper]({{< ref "/publication/riddell-2018-aa/index.md" >}}) on gun violence in US states by [CNN](https://www.cnn.com/2018/04/23/health/gun-deaths-in-men-by-state-study/index.html), 2018-04-23.
- NPR's *Hidden Brain*
[story](https://www.tpr.org/post/hidden-brain-great-recession-deaths) on our [paper]({{< ref "/publication/strumpf-2017-aa/index.md" >}}) looking at the impact of recessions on mortality, 2018-01-16.
- PBS NewsHour [coverage](https://www.pbs.org/newshour/nation/click-it-or-ticket-seat-belt-laws) of our [work]({{< ref "/publication/harper-2017-ac/index.md" >}}) on seat belt laws and traffic crash mortality, 2017-04-30. 
